### ISSUE TITLE
Changes not staged for commit

### ISSUE THREAD

**Issue by antongolub** [dhoulb/multi-semantic-release#1]
Hi there. Nice to know that someone else is trying to make semantic monorepos.

Anyway, the problem.

When sem-rel-git plugin is enabled, git push fails because of not staged changes.

release config
```json
{
    "branch": "master",
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      "@semantic-release/npm",
      [
        "@semantic-release/git",
        {
          "assets": [
            "src/**/*.{js,css}",
            "package.json"
          ],
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
        }
      ],
      "@semantic-release/github"
    ]
  }
```
[build log](https://travis-ci.com/antongolub/release-testing/builds/104051251)
```
[11:24:10 AM] [@antongolub/release-testing-package-second] › ✖  An error occurred while running semantic-release: { Error: Command failed: git commit -m chore(release): 1.0.1 [skip ci]
## @antongolub/release-testing-package-second [1.0.1](https://github.com/antongolub/release-testing.git/compare/@antongolub/release-testing-package-second@1.0.0...@antongolub/release-testing-package-second@1.0.1) (2019-03-12)
### Performance Improvements
* tech release ([c7e9bfa](https://github.com/antongolub/release-testing.git/commit/c7e9bfa))
* tech release ([f911408](https://github.com/antongolub/release-testing.git/commit/f911408))
HEAD detached from d185edf
Changes not staged for commit:
	modified:   ../../bar/release-testing-package-fourth/CHANGELOG.md
	modified:   ../release-testing-package-first/CHANGELOG.md
	modified:   CHANGELOG.md
	modified:   ../release-testing-package-third/CHANGELOG.md
```
I have no idea, how to handle this case. Sem-rel core pushes tags right after `prepare` step
```javascript
await plugins.prepare(context);

  if (options.dryRun) {
    logger.warn(`Skip ${nextRelease.gitTag} tag creation in dry-run mode`);
  } else {
    // Create the tag before calling the publish plugins as some require the tag to exists
    await tag(nextRelease.gitTag, {cwd, env});
    await push(options.repositoryUrl, {cwd, env});
    logger.success(`Created tag ${nextRelease.gitTag}`);
  }
```

**Comment by dhoulb** [comment]
Hmmmmmm — I've done a _very quick_ look into this and if I think it's because multiple `git` CLI calls are being made simultaneously. I had to do some hacks to avoid this in the package to make sure the tag pushing calls were staggered — but I didn't do it for the `prepare` step.

This is because internally to `semantic-release` and `@semantic-release/git`, `git push` etc are called  asyncronously (using the `exec()` method). The easy fix would be for `semantic-release` to just use `exec.sync()` instead. 

I don't want to fix this in `multi-semantic-release` since this project is just a POC for learning and I don't want to invest time into it (I'd happily accept PRs though). 

I'm still hoping to get `semantic-release` to [take my recommendations](https://github.com/semantic-release/semantic-release/issues/193#issuecomment-462063871) and bake in monorepo support natively! I'm hoping to get some availability to prep a PR for that at some point. I've noted the need to change `execa()` to `execa.sync()` (which would fix this issue), and it seems like that would need to be changed in `@semantic-release/git` too.

**Comment by antongolub** [comment]
Oook — I've tested the hypothesis of replacing [`execa` calls with`execa.sync`](https://github.com/antongolub/release-testing/commit/b7b80067eca4030fe38bf5ec1a64e3caf15f6c19) with dirty module hook. 
```javascript
const execa = require('execa')
const hook = require('require-in-the-middle')
const { sync, stdout, stderr, shell, shellSync } = execa

const _execa = (...args) => {
  const result =  new Promise((resolve, reject) => {
    try {
      resolve(sync(...args))
    } catch (e) {
      reject(e)
    }
  })

  result.stdout.pipe = () => {}
  result.stderr.pipe = () => {}
}


Object.assign(_execa, execa)
_execa.sync = sync
_execa.stdout = stdout
_execa.stderr = stderr
_execa.shell = shell
_execa.shellSync = shellSync

delete require.cache[require.resolve('execa')]

hook(['execa'], () => _execa)

require('multi-semantic-release/bin/cli')
```
And here's [what happens next](https://github.com/antongolub/release-testing/issues/2):
* sem-rel asserts tagFormat
* checks that working directory matches to the project root

**Comment by antongolub** [comment]
I've missed the `return`... and it definitely [looks good now](https://travis-ci.com/antongolub/release-testing/builds/104479780)

**Comment by dhoulb** [comment]
Anton thanks so much for testing, that's extremely useful to know! 

It **would be possible** then to fix this in `multi-semantic-release` too by serializing the calls to `plugins.prepare()` with some hacky `Promise` manipulation. I don't know if that's worth doing, but it's great to have the hypothesis confirmed!
