### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by antongolub** [dhoulb/multi-semantic-release#30]
* describe `synchronizer` effects and limitations
* mention argv flags
* correct `inlinePlugin` description

**Comment by antongolub** [comment]
@dhoulb, any objections?

**Comment by antongolub** [comment]
Ok, that's reasonable.  I will try other alternatives: codacy, codefactor, sonar, etc.

I just wanted to add code quality checks to pull requests. Thank you for your trust, but this is definitely not a reason for a transfer)) Perhaps someday later, we will have a more weighty reason to assemble several projects in one organization:
* https://github.com/qiwi/semantic-release-toolkit
* https://github.com/antongolub/zx-semrel
* https://github.com/qiwi/semantic-release-gh-pages-plugin
* https://github.com/dhoulb/multi-semantic-release
* https://github.com/qiwi/multi-semantic-release
* https://github.com/antongolub/release-testing

But we are very very far from this right now.

**Comment by dhoulb** [comment]
@antongolub Looks like you made some progress on this? Setting up the new org? 😁 

I can transfer the repo to the org if you’re happy for me to do so? I’ll probably also update deployment to use GitHub actions instead of Travis too at the same time, and I’ll add you to the package on npm too so you have full access. Might take me a couple weeks to get round to it.

**Comment by antongolub** [comment]
@dhoulb,

Yes. I'm currently setting up a basic technical landscape, if I may say so. I've done very little yet:
- Created @semrel-extra org
- Registered @semrel-extra-bot to delegate routine operations to it. email + github + npm + gravatar + 2fa + so on
- Generated bot tokens, put them to org secrets
