### ISSUE TITLE
Override asterisk version

### ISSUE THREAD

**Issue by IgorBabkin** [dhoulb/multi-semantic-release#37]
MSR overrides local dependency version even if it's an asterisk "*". It raises an error on GitlabCI because MSR releases packages in random sequence. Is possible to not touch an asterisk version? Or release packages sequently (release dependent packages only in the last step)

![image](https://user-images.githubusercontent.com/1428790/94347947-cf3d4600-0038-11eb-878c-aff903897229.png)
![image](https://user-images.githubusercontent.com/1428790/94347955-dc5a3500-0038-11eb-8d17-ba93a9258a38.png)

**Comment by antongolub** [comment]
Hey, @IgorBabkin,

I think we could make the cross-update policy configurable. **msr** updates the entire package chain as patches, but in some cases I'd like to inherit the update type (major, minor, breaking change) for descendants, or even stop further updates.

```js
function hasChangedDeep(packages, ignore = []) {
	// Has changed if...
	return packages
		.filter((p) => ignore.indexOf(p) === -1)
		.some((p) => {
			// 1. Any local dep package itself has changed
			if (p._nextType) return true;
			// 2. Any local dep package has local deps that have changed.
			else if (hasChangedDeep(p._localDeps, [...ignore, ...packages])) return true;
			// Nope.
			else return false;
		});
}
  //...
  // Make sure type is "patch" if the package has any deps that have changed.
   if (!pkg._nextType && hasChangedDeep(pkg._localDeps)) pkg._nextType = "patch";
```

**Comment by IgorBabkin** [comment]
@antongolub I haven't caught you. What I want:
package b
| - package a

package c
| - package a

I want to update and commit version of package a firstly. And only after that we can update package b and package c. Now MSR uses flat updating by `Promise.all` iterating over all packages. I would like to iterate over the dependency tree. OR we can use asterisk version as MSR recommends. But I don't understand why does it change asterisk version to semantic one during `multi-semantic-release`?

**Comment by antongolub** [comment]
@IgorBabkin

As I can see, the current implementation does not handle `*` case at all. Unfortunately, we have extremely few resources to deal with this problem right now, but if you make a PR, we will definitely help to finalize it.

**Comment by dhoulb** [comment]
@IgorBabkin 

MSR recommends using the asterisk (and committing the asterisk) so that when you're developing locally the connections between all the packages always use the latest version.

MSR, when publishing, always changes the asterisks to the fixed versions to lock in the exact web of local dependencies that is known to work. Package B saying "I don't care what version of Package A is installed" probably doesn't make sense? Even a minor version difference could cause A and B to be incompatible.

You've made a great suggestion about optimising the release order of packages to minimise cases where a package relies on a local dependency version that is not yet available. It's something we would definitely consider down the line if we do a big rewrite, or that we'd accept in a PR. But not something we currently have resources to work on personally.

Please bear in mind this project isn't designed to be a full solution, it's rough and ready and works for now (since there is currently nothing better), but ideally will some day replaced!
